### ISSUE TITLE
id has full path

### ISSUE THREAD

**Issue by elwynelwyn** [lceric/vite-plugin-resolve-externals#1]
I'm not sure if I am using this plugin correctly, but it seems to be the thing I need.
I have `externals` configured in rollupOptions for the production build, to make my code use external `window.React` when import from `react`  is found in code, and I need this same functionality to work at development time (same issue as https://github.com/vitejs/vite/issues/544 )

I have added this plugin like:
```
    resolveExternalsPlugin({
        react: "React",
        "react-dom": "ReactDOM"
    }),
```
However at runtime in development I can see the ID that is being passed to the plugin has an absolute path to the file on disk, e.g.:

```
'C:/MyRepo/node_modules/.vite/react.js?v=9cf5b81e',
```
This means the ID never matches the `externals` object, so the plugin code is never returned.

Any suggestions on what I'm doing incorrectly?

**Comment by lceric** [comment]
I'm sorry, but I didn't repeat this problem on windows.

I wrote [a react simple demo](https://github.com/lceric/vite-plugin-resolve-externals/blob/main/example/react-demo/vite.config.js) in the sample directory, hoping to help you.

```js
const path = require('path')
const { defineConfig } = require('vite')
const reactRefresh = require('@vitejs/plugin-react-refresh')
const resolveExternalsPlugin = require('vite-plugin-resolve-externals')
const projectRootDir = path.resolve(__dirname)

// https://vitejs.dev/config/
export default defineConfig({
  jsx: 'react',
  plugins: [
    reactRefresh(),
    resolveExternalsPlugin({
      react: 'React',
      'react-dom': 'ReactDOM',
    }),
  ],
  resolve: {
    alias: [
      {
        find: '@',
        replacement: path.resolve(projectRootDir, 'src'),
      },
    ],
  },
})
```

**Comment by elwynelwyn** [comment]
It must be something we're doing in our project then! Thanks for checking.

I have worked around the issue for now by modifying your plugin to handle this situation:

```
function resolveExternalsPlugin(
    externals: Record<string, string> = {}
) {
    const extractId = (id: string): string => {
        // match blah/node_modules/.vite/foo.js?1234
        const match = id.match(/^.*\/node_modules\/\.vite\/(.+)\.js.*$/i);
        if (match && match.length === 2) {
            return match[1];
        }

        return id;
    };

    return {
        name: "vite-plugin-resolve-externals",
        config(config: UserConfig) {
            const { resolve } = config;
            Object.assign(externals, resolve.externals);
            return config;
        },
        resolveId(path: string) {
            const id = extractId(path);
            if (externals[id]) {
                return id;
            }
        },
        load(path: string) {
            const id = extractId(path);
            if (externals[id]) {
                return `const externals = window.${externals[id]};
    export default externals`;
            }
        },
    };
}
```
