### ISSUE TITLE
ReferenceError: keys is not defined

### ISSUE THREAD

**Issue by lizifa** [lceric/vite-plugin-resolve-externals#5]
config(config) {
      // Merge externals from `config.resolve`
      Object.assign(externals, config.resolve.externals);

      if (!config.optimizeDeps) config.optimizeDeps = {};
      if (!config.optimizeDeps.exclude) config.optimizeDeps.exclude = [];

      let exclude = Object.keys(externals);
      if (config.optimizeDeps.include) {
        // If the user force the module to be Pre-building, we should filter out it
        exclude = keys.filter(key => !config.optimizeDeps.include.includes(key));
      }
      // Avoid vite Pre-building
      config.optimizeDeps.exclude.push(...exclude);
    },

大佬 keys is not define
![微信图片_20220425202540](https://user-images.githubusercontent.com/20900894/165088564-658916aa-dc6e-4b88-807f-97a651d17a2b.png)
d

**Comment by lceric** [comment]
Thank you, please update and use `vite-plugin-resolve-externals@0.2.2`
